### ISSUE TITLE
Create Contributor Guide Lines

### ISSUE THREAD

**Issue by Ank221199** [Ank221199/WorkoutGenerator#1]

**Comment by Ank221199** [comment]
Reference: 
https://opensource.com/life/16/3/contributor-guidelines-template-and-tips

**Comment by AdarshCoder397** [comment]
Hey @Ank221199 , I can work on this!

**Comment by Ank221199** [comment]
Ok you start I will assign this to you

**Comment by proffapt** [comment]
solved in #20
