### ISSUE TITLE
Need Logo for the project 

### ISSUE THREAD

**Issue by Ank221199** [Ank221199/WorkoutGenerator#5]
##  LOGO

* The logo should be related to workout/gym/active lifestyle 
* It should contain my initials or ANK
* Design should be either Retro/futuristic

**Comment by KaranSinghBisht** [comment]
Hey Ank, I would love to work on this issue!

**Comment by KaranSinghBisht** [comment]
Hey @Ank221199, I worked on a couple of designs, please tell me what you think and what tweaks/changes can be made. 
![Logo 1 2](https://user-images.githubusercontent.com/69008866/193394513-557fb3f1-5317-4317-99cf-8ca8d41036fb.png)
![Logo 1 12](https://user-images.githubusercontent.com/69008866/193394514-182fe177-508b-472b-9dd6-c06222bdc259.png)
![Logo 2](https://user-images.githubusercontent.com/69008866/193394515-409e9758-6a12-47fe-84e1-b78f38e45593.png)
![Logo 1 1](https://user-images.githubusercontent.com/69008866/193394517-2ebcfd6c-7c39-4b4a-8810-fc3be68c9f51.png)

**Comment by Ank221199** [comment]
I really like these two :
![image](https://user-images.githubusercontent.com/40303711/193397269-56c8dbc2-8bb3-4eb9-bc74-7655ea68840b.png)
![image](https://user-images.githubusercontent.com/40303711/193397272-eb77959f-1343-4171-bed6-b45a410227c6.png)


Can you use the design/aesthetic of 1st image with a pattern of 2nd

**Comment by Ank221199** [comment]
Also, it would be much appreciated if you can add a touch of orange [#e39f20]

**Comment by KaranSinghBisht** [comment]
Well the first one is futuristic and the second is retro, you want the colors of 1st in the second? Thank you.

**Comment by Ank221199** [comment]
Color and Look of a futuristic one 

Pattern/design of the second one 


In short, make the retro logo look futuristic 😅

**Comment by KaranSinghBisht** [comment]
![Asset 12](https://user-images.githubusercontent.com/69008866/193425310-f1b45cb1-c893-44d4-a020-9c9b5424e5ee.png)
![Asset 13](https://user-images.githubusercontent.com/69008866/193425313-538f465f-8701-41ec-851c-334692d30673.png)
![Asset 10](https://user-images.githubusercontent.com/69008866/193425315-eaf06447-7b76-40fd-9513-e8df41c5f2e5.png)
![Asset 11](https://user-images.githubusercontent.com/69008866/193425317-1030fc2a-e2a2-4dee-864b-e15ff1a347bc.png)

Do tell me if I misinterpreted your suggestion, as I am a little confused.😅

**Comment by sowmiya-venkatesan** [comment]
I'd love to contribute to this issue, please assign it to me @Ank221199

**Comment by KaranSinghBisht** [comment]
@Ank221199 any updates?

**Comment by Ank221199** [comment]
@KaranSinghBisht, Its Perfect, can you push all the three logo (SVG preferred )
